import Head from "next/head";
import Image from "next/image";
import localFont from "next/font/local";
import clsx from "clsx";
import { useEffect, useMemo, useState } from "react";
import { motion } from "framer-motion";

const formatter = new Intl.NumberFormat("en-US");

// Font files can be colocated inside of `pages`
const sentient = localFont({ src: "Sentient-Variable.ttf" });

function calculateDuration() {
  const now = new Date();
  const endDate = new Date("2023-06-03T15:33:00-07:00");
  const excludedDates = [
    new Date("2023-04-03"),
    new Date("2023-04-04"),
    new Date("2023-04-05"),
    new Date("2023-04-06"),
    new Date("2023-04-07"),
    new Date("2023-05-15"),
    new Date("2023-05-29"),
  ];

  let duration = 0;

  while (now < endDate) {
    const dayOfWeek = now.getDay();

    const isExcludedDate = excludedDates.some((excludedDate) => {
      return now.toDateString() === excludedDate.toDateString();
    });

    if (!isExcludedDate) {
      const startOfDay = new Date(now);
      startOfDay.setHours(dayOfWeek === 1 ? 10 : 8, 30, 0, 0); // 10am on Monday, 8:30am on other days

      const endOfDay = new Date(now);
      endOfDay.setHours(15, 33, 0, 0);

      if (dayOfWeek !== 0 && dayOfWeek !== 6) {
        if (now < startOfDay || now > endOfDay) {
          duration += endOfDay.getTime() - startOfDay.getTime();
        } else {
          duration += endOfDay.getTime() - now.getTime();
          now.setHours(15, 33, 0, 0);
        }
      }
    }

    now.setHours(now.getHours() + 24);
    now.setMinutes(0, 0, 0);
  }

  return duration;
}

function calculateDays() {
  const now = new Date();
  const endDate = new Date("2023-06-03T15:33:00-07:00");
  const excludedDates = [
    new Date("2023-04-03"),
    new Date("2023-04-04"),
    new Date("2023-04-05"),
    new Date("2023-04-06"),
    new Date("2023-04-07"),
    new Date("2023-05-15"),
    new Date("2023-05-29"),
  ];

  let days = 0;

  while (now < endDate) {
    const dayOfWeek = now.getDay();

    const isExcludedDate = excludedDates.some((excludedDate) => {
      return now.toDateString() === excludedDate.toDateString();
    });

    if (!isExcludedDate) {
      const startOfDay = new Date(now);
      startOfDay.setHours(dayOfWeek === 1 ? 10 : 8, 30, 0, 0); // 10am on Monday, 8:30am on other days

      const endOfDay = new Date(now);
      endOfDay.setHours(15, 33, 0, 0);

      if (dayOfWeek !== 0 && dayOfWeek !== 6) {
        if (now < startOfDay || now > endOfDay) {
          days += 1;
        } else {
          days += 1;
          now.setHours(15, 33, 0, 0);
        }
      }
    }

    now.setHours(now.getHours() + 24);
    now.setMinutes(0, 0, 0);
  }

  return days;
}

const inSchoolNow = () => {
  // returns a boolean if the current time is during school hours
  const now = new Date();
  const endDate = new Date("2023-06-03T15:33:00-07:00");
  const excludedDates = [
    new Date("2023-04-03"),
    new Date("2023-04-04"),
    new Date("2023-04-05"),
    new Date("2023-04-06"),
    new Date("2023-04-07"),
    new Date("2023-05-15"),
    new Date("2023-05-29"),
  ];

  const dayOfWeek = now.getDay();

  const isExcludedDate = excludedDates.some((excludedDate) => {
    return now.toDateString() === excludedDate.toDateString();
  });

  if (!isExcludedDate) {
    const startOfDay = new Date(now);
    startOfDay.setHours(dayOfWeek === 1 ? 10 : 8, 30, 0, 0); // 10am on Monday, 8:30am on other days

    const endOfDay = new Date(now);
    endOfDay.setHours(15, 33, 0, 0);

    if (dayOfWeek !== 0 && dayOfWeek !== 6) {
      if (now < startOfDay || now > endOfDay) {
        return false;
      } else {
        return true;
      }
    }
  }

  return false;
};

export default function Home() {
  const duration = useMemo(() => calculateDuration(), []);
  const days = useMemo(() => calculateDays(), []);

  const [seconds, setSeconds] = useState(duration / 1000);
  const [inSchool, setInSchool] = useState(inSchoolNow());

  const formattedSeconds = formatter.format(seconds);
  const formattedMinutes = formatter.format(Math.floor(seconds / 60));
  const formattedHours = formatter.format(Math.floor(seconds / 60 / 60));
  const formattedDays = formatter.format(days);

  useEffect(() => {
    if (duration <= 0) {
      return;
    }

    const interval = setInterval(() => {
      if (inSchoolNow()) {
        setSeconds((seconds) => seconds - 1);
        setInSchool(true);
      } else {
        setInSchool(false);
      }
    }, 1000);

    return () => clearInterval(interval);
  }, [duration]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main
        className={clsx(
          "w-full h-screen bg-neutral-900 text-white flex flex-col space-y-2 text-4xl items-center justify-center",
          sentient.className
        )}
      >
        <div className="flex flex-col space-y-2 items-center relative p-2 text-center">
          <motion.h1 className="text-6xl overflow-hidden leading-none">
            {formattedDays.split("").map((char, index) => {
              return (
                <motion.span
                  className="inline-block"
                  key={char + index}
                  initial={{ y: "1em" }}
                  animate={{ y: 0 }}
                  transition={{
                    type: "spring",
                    stiffness: 400,
                    damping: 35,
                    delay: (formattedDays.length - index) * 0.1,
                  }}
                >
                  {char}
                </motion.span>
              );
            })}{" "}
            <span className="text-4xl">school days</span>
          </motion.h1>
          <motion.h2 className="text-4xl overflow-hidden leading-none">
            {formattedHours.split("").map((char, index) => {
              return (
                <motion.span
                  className="inline-block"
                  key={char + index}
                  initial={{ y: "1em" }}
                  animate={{ y: 0 }}
                  transition={{
                    type: "spring",
                    stiffness: 400,
                    damping: 35,
                    delay: (formattedHours.length - index) * 0.1,
                  }}
                >
                  {char}
                </motion.span>
              );
            })}{" "}
            hours
          </motion.h2>
          <motion.h3 className="text-2xl overflow-hidden leading-none">
            {formattedMinutes.split("").map((char, index) => {
              return (
                <motion.span
                  className="inline-block"
                  key={char + index}
                  initial={{ y: "1em" }}
                  animate={{ y: 0 }}
                  transition={{
                    type: "spring",
                    stiffness: 400,
                    damping: 35,
                    delay: (formattedMinutes.length - index) * 0.1,
                  }}
                >
                  {char}
                </motion.span>
              );
            })}{" "}
            minutes
          </motion.h3>
          <motion.h4 className="text-xl overflow-hidden leading-none">
            {formattedSeconds.split("").map((char, index) => {
              return (
                <motion.span
                  className="inline-block"
                  key={char + index}
                  initial={{ y: "1em" }}
                  animate={{ y: 0 }}
                  transition={{
                    type: "spring",
                    stiffness: 400,
                    damping: 35,
                    delay: (formattedSeconds.length - index) * 0.1,
                  }}
                >
                  {char}
                </motion.span>
              );
            })}{" "}
            seconds
          </motion.h4>

          {!inSchool && (
            <span className="text-sm text-neutral-400 pt-4">
              The timer only counts when school is in session.
            </span>
          )}
          <span className="text-sm">
            Made by{" "}
            <a
              href="https://eliothertenstein.com"
              target="_blank"
              rel="noopener noreferrer"
            >
              Eliot
            </a>
          </span>
        </div>
      </main>
    </>
  );
}
